version: "3.8"

volumes:
  rabbitmq_data:

services:
  ##################################
  # Price: The Price microservice
  ##################################
  price:
    build:
      context: ./
      dockerfile: price.Dockerfile
    image: <dockerid>/price:eevee
    restart: always
    environment:
      price_URL: http://price:5000/price
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"
      
  ##################################
  # Swap: The Swap microservice
  ##################################
  swap:
    build: 
      context: ./
      dockerfile: swap.Dockerfile
    image: <dockerid>/swap:eevee
    restart: always
    environment:
      swap_URL: http://swap:5000/swap
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5004"

  ##################################
  # Authenticate: The Authenticate microservice
  ##################################
  authenticate:
    build: 
      context: ./
      dockerfile: swap.Dockerfile
    image: <dockerid>/authenticate:eevee
    restart: always
    environment:
      authenticate_URL: http://authenticate:5000/authenticate
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5004"


  ##################################
  # Transaction Log: The Transaction Log microservice
  ##################################
  transactionLog:
    build: 
      context: ./
      dockerfile: transactionLog.Dockerfile
    image: <dockerid>/transactionLog:eevee
    restart: always
    environment:
      transactionLog_URL: http://transactionLog:5000/transactionLog
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5004"
      
  ##################################
  # Make Transaction: The Make Transaction microservice
  ##################################
  makeTransaction:
    build: 
      context: ./
      dockerfile: makeTransaction.Dockerfile
    image: <dockerid>/makeTransaction:eevee
    restart: always
    environment:
      makeTransaction_URL: http://makeTransaction:5000/makeTransaction
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5004"