version: "3.8"

volumes:
  rabbitmq_data:

services:
  ##################################
  # App: The App Interface
  ##################################
  interface:
    build:
      context: ./
      dockerfile: app.Dockerfile
    image: janeleq/app:eevee
    restart: always
    depends_on:
      - price
      - authenticate
      - swap
      - topup
      - make_transaction
      - transaction_log
    environment:
      # price_URL: http://price:5000/price
      PYTHONUNBUFFERED: 1
    ports: 
      - 5000:5000
      
  ##################################
  # Price: The Price microservice
  ##################################
  price:
    build:
      context: ./
      dockerfile: price.Dockerfile
    image: janeleq/price:eevee
    restart: always
    environment:
      # price_URL: http://price:5000/price
      PYTHONUNBUFFERED: 1
    ports: 
      - 5001:5000


  ##################################
  # Topup: The Topup microservice
  ##################################
  topup:
    build: 
      context: ./
      dockerfile: topup.Dockerfile
    image: janeleq/topup:eevee
    restart: always
    environment:
      # topup_URL: http://topup:5000/process_topup
      PYTHONUNBUFFERED: 1
    ports: 
      - 5005:5000

      
  ##################################
  # Swap: The Swap microservice
  ##################################
  swap:
    build: 
      context: ./
      dockerfile: swap.Dockerfile
    image: janeleq/swap:eevee
    restart: always
    depends_on:
      - price
    environment:
      # swap_URL: http://swap:5000/swap
      PYTHONUNBUFFERED: 1
    ports: 
      - 5004:5000

  ##################################
  # Authenticate: The Authenticate microservice
  ##################################
  authenticate:
    build: 
      context: ./
      dockerfile: authenticate.Dockerfile
    image: janeleq/authenticate:eevee
    restart: always
    environment:
      # authenticate_URL: http://authenticate:5000/authenticate
      PYTHONUNBUFFERED: 1
    ports: 
      - 5050:5000


  ##################################
  # Transaction Log: The Transaction Log microservice
  ##################################
  transaction_log:
    build: 
      dockerfile: transaction_log.Dockerfile
    image: janeleq/transactionlog:eevee
    restart: always
    environment:
      # transactionLog_URL: http://transactionLog:5000/transactions
      PYTHONUNBUFFERED: 1
    ports: 
      - 5006:5000
    
  ##################################
  # Make Transaction: The Make Transaction microservice
  ##################################
  make_transaction:
    build: 
      context: ./
      dockerfile: make_transaction.Dockerfile
    image: janeleq/maketransaction:eevee
    restart: always
    depends_on:
      - price
    environment:
      # makeTransaction_URL: http://makeTransaction:5000/makeTransaction
      PYTHONUNBUFFERED: 1
    ports: 
      - 5010:5000
